CREATE DATABASE PROJECT_2001_CENSUS

USE  PROJECT_2001_CENSUS
 
SELECT * FROM DATA11
SELECT * FROM DATA22

--- NO OF ROWS
SELECT COUNT(*) FROM  DATA11
SELECT COUNT(*) FROM  DATA22

--- DATASET FOR KARNATAKA AND GUJARAT

SELECT * 
FROM DATA11
WHERE STATE='KARNATAKA' OR STATE='GUJARAT' ;

---TOTAL POPULATION OF INDIA

SELECT SUM(POPULATION) FROM DATA22 

---AVERAGE GROWTH OF POPULATION OF INDIA 

SELECT AVG(GROWTH)*100 FROM DATA11

---AVERAGE GROWTH OF POPULATION OF STATE

SELECT STATE, AVG(GROWTH)*100 FROM DATA11 GROUP BY STATE

---AVERAGE SEX RATIO OF EACH STATE

SELECT STATE, ROUND(AVG(SEX_RATIO),0) AS AVG_SEX_RATIO_PER_1000_MEN  FROM DATA11 GROUP BY STATE 
 ORDER BY AVG_SEX_RATIO_PER_1000_MEN DESC;
  
 ---AVERAGE LITERACY RATE OF EACH STATE

SELECT STATE, ROUND(AVG(LITERACY),0) AS AVG_LITERACY  FROM DATA11 GROUP BY STATE 
 ORDER BY AVG_LITERACY DESC; 
 
 SELECT STATE, ROUND(AVG(LITERACY),0) AS AVG_LITERACY FROM DATA11 GROUP BY STATE 
 HAVING ROUND(AVG(LITERACY),0) >90 ORDER BY AVG_LITERACY DESC 
 
---AVERAGE GROWTH OF POPULATION OF TOP 3 STATES

SELECT  STATE, AVG(GROWTH)*100 AS AVG_GROWTH FROM DATA11 GROUP BY STATE ORDER BY AVG_GROWTH DESC LIMIT 3 

---LOWEST AVERAGE SEX RATIO OF BOTTOM STATE

SELECT STATE, ROUND(AVG(SEX_RATIO),0) AS AVG_SEX_RATIO_PER_1000_MEN  FROM DATA11 GROUP BY STATE 
 ORDER BY AVG_SEX_RATIO_PER_1000_MEN ASC LIMIT 3
 
         

---JOINING BOTH TABLES DATA11 AND DATA22

SELECT A.DISTRICT,A.STATE,A.SEX_RATIO,B.POPULATION FROM DATA11 AS A
INNER JOIN DATA22 AS B
ON A.DISTRICT=B.DISTRICT 

---STATES STARTING WITH A E I O U VOWELS

SELECT STATE
FROM DATA11
WHERE STATE LIKE 'A%'
OR STATE LIKE 'E%' 
OR STATE LIKE 'I%' 
OR STATE LIKE 'O%' 
OR STATE LIKE 'U%'

---- FORMULAS TO FIND NO OF MALE AND FEMALE
 FEMALE/MALES=SEX_RATIO ---1
FEMALE+MALES=POPULATION ---2
FEMALES=POPULATION-MALES ---3
POPULATION-MALES=SEX_RATIO*MALES
POPULATION=MALES*(SEX_RATIO+1)
MALES=POPULATION/(SEX_RATIO+1)
FEMALES=POPULATION-(POPULATION/(SEX_RATIO+1))

---- NO OF TOTAL MALES AND NO OF TOTAL FEMALES BY STATES

SELECT D.STATE,SUM(D.MALES) AS TOTAL_MALES,SUM(D.FEMALES) AS TOTAL_FEMALES FROM 
(SELECT DISTRICT,STATE,ROUND(POPULATION/(SEX_RATIO+1),0) AS MALES, ROUND(POPULATION-(POPULATION/(SEX_RATIO+1)),0) AS FEMALES FROM
(SELECT A.DISTRICT,A.STATE,A.SEX_RATIO/1000 AS SEX_RATIO,B.POPULATION FROM DATA11 AS A
INNER JOIN DATA22 AS B
ON A.DISTRICT=B.DISTRICT ) C ) D 
GROUP BY D.STATE

----TOTAL LITERACY RATE BY STATES

SELECT C.STATE,SUM(LITERATE_PEOPLE) AS TOT_LITERATE_PEOPLE,SUM(ILLITERATE_PEOPLE) AS TOT_ILLITERATE_PEOPLE FROM
(SELECT D.DISTRICT,D.STATE,ROUND(D.LITARACY_RATIO*D.POPULATION,0) AS LITERATE_PEOPLE, ROUND((1-D.LITARACY_RATIO)*D.POPULATION,0) AS ILLITERATE_PEOPLE FROM
(SELECT A.DISTRICT,A.STATE,A.LITERACY/100 AS LITARACY_RATIO,B.POPULATION FROM DATA11 AS A
INNER JOIN DATA22 AS B
ON A.DISTRICT=B.DISTRICT) D) C 
GROUP BY C.STATE

----POPULATION IN PREVIOUS SENSUS USING THIS YEARS'S GROWTH RATE


SELECT SUM(M.PREVIOUS_YEAR_CENSUS_POPULATION), SUM(M.CURRENT_CENSUS_POPULATION) FROM
(SELECT E.STATE,SUM(E.PREVIOUS_YEAR_CENSUS_POPULATION) AS PREVIOUS_YEAR_CENSUS_POPULATION,SUM(E.CURRENT_CENSUS_POPULATION)  AS CURRENT_CENSUS_POPULATION FROM
(SELECT D.DISTRICT,D.STATE,ROUND(D.POPULATION/(1+D.GROWTH),0)AS PREVIOUS_YEAR_CENSUS_POPULATION, D.POPULATION AS CURRENT_CENSUS_POPULATION FROM
(SELECT A.DISTRICT,A.STATE,A.GROWTH AS GROWTH,B.POPULATION FROM DATA11 AS A
INNER JOIN DATA22 AS B
ON A.DISTRICT=B.DISTRICT) D) E
GROUP BY E.STATE ) M

-----WINDOW FUNCTIONS

----TOP 3 DISTRICT FROM EACH STATE WITH HIGHEST LITERACY RATE USING WINDOW FUNCTION


SELECT A.* FROM
(SELECT DISTRICT,STATE,LITERACY,RANK() OVER(PARTITION BY STATE ORDER BY LITERACY DESC) AS RANKS FROM DATA11) A
WHERE A.RANKS IN (1,2,3) ORDER BY STATE





 



 

